variables:
  PIPELINE_RUNNER: python:3.9
  DOCKER_RUNNER: 20.10.13-dind-alpine3.15

cache:
  paths:
    - src/django_orm/venv

stages:
  - test
  - docker-test

# Disabled to speed up docker-test
# test:
#   image: ${PIPELINE_RUNNER}
#   stage: test
#   script:
#       - cd src/django_orm
#       - python3 -m venv venv
#       - source venv/bin/activate
#       - pip install -r requirements.txt -c constraints.txt
#       - pytest

docker-test:
  image: ${DOCKER_RUNNER}
  tags: 
    - docker
    - dind
    - docker-compose
  stage: docker-test
  script:
    - docker ps

