image: python:3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - deploy

pages:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - mkdocs build
  artifacts:
    paths:
      - site
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

