

stages:
  - test
  - deploy

unit-tests:
  image: docker:20.10.21-cli
  stage: test
  script:
    - apk add python3
    - ./make ci_test

pages:
  image: python:3.10
  stage: deploy
  needs:
    - unit-tests
  script:
    - pip install -r requirements.txt
    - ./make shell_docs_build
    - mv site public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

