variables:
  PIPELINE_RUNNER: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - src/django_orm/venv

stages:
  - test

test:
  image: ${PIPELINE_RUNNER}
  stage: test
  script:
      - cd src/django_orm
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt -c constraints.txt
      - pytest