variables:
  PIPELINE_RUNNER: python:3.9
  DOCKER_RUNNER: docker:20.10.13-dind-alpine3.15

cache:
  paths:
    - src/django_orm/venv

stages:
  - docker-check
  - docker-test

docker-test:
  image: ${PIPELINE_RUNNER}
  stage: docker-test
  script:
      - cd src/django_orm
      - docker login $docker_registry -u $docker_username -p $docker_registry_token
      - docker pull -t $image_name:test
      - docker build -t $image_name:test .
      - docker push -t $image_name:test
      - docker run $image_name:test pytest
  variables:
    image_name: gitlab.noveogroup.com:4567/trainings-anovoselov/trainings-anovoselov-postgersql

