version: '3.5'

services:
  db:
    image: postgres:15-bullseye
    # command: postgres -c shared_buffers=16 -c effective_cache_size=1 -c plan_cache_mode='force_custom_plan'
    # command: postgres -c log_statement=mod -c log_duration=on
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER:-postgres}" ]
      interval: 3s
      timeout: 3s
      retries: 5
    ports:
      - 5432:5432