version: '3.5'

services:
  app: &app
    build: .
    environment:
      TRAINING_DATABASE_USERNAME: "postgres"
      TRAINING_DATABASE_PASSWORD: "postgres"
      TRAINING_DATABASE_HOST: "db"
      TRAINING_LOGGER_CONSOLE_LEVEL: "DEBUG"
    depends_on:
      - db
    command: sh
  db:
    image: postgres:15-bullseye
    # command: postgres -c shared_buffers=16 -c effective_cache_size=1 -c plan_cache_mode='force_custom_plan'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
  app_with_pgadmin:
    <<: *app
    depends_on:
      - db
      - pgadmin

  