version: '3.5'

services:
  app:
    build: .
    environment:
      TRAINING_DATABASE_USERNAME: "postgres"
      TRAINING_DATABASE_PASSWORD: "postgres"
      TRAINING_DATABASE_HOST: "db"
      TRAINING_LOGGER_CONSOLE_LEVEL: "DEBUG"
    depends_on:
      - db
    command: sh
    volumes:
      - ".:/code"
    working_dir: /code
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"