version: '3'

tasks:
  test:
    cmds:
      - go clean -cache
      - go clean -testcache
      - go test ./... -count=1 -a {{.CLI_ARGS}}

  db:run:
    cmds:
      - docker-compose up -d db
  db:down:
    cmds:
      - docker-compose down --remove-orphans --volumes
  