version: '3'

tasks:
  down:
    internal: true
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} down

  build:
    internal: true
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} build -- app
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} build 

  up:
    internal: true
    cmds:
      - defer: { task: down, vars: { COMPOSE_ID: "{{.COMPOSE_ID}}"} }
      - task: build
        vars: { COMPOSE_ID: "{{.COMPOSE_ID}}"}
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} up

  run:
    internal: true
    cmds:
      - echo "{{.COMPOSE_ID}}"
      - defer: { task: down, vars: { COMPOSE_ID: "{{.COMPOSE_ID}}"} }
      - task: build
        vars: { COMPOSE_ID: "{{.COMPOSE_ID}}"}
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} run {{.CMD}}

  ci_run:
    internal: true
    cmds:
      - defer: docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} down --volumes --rmi local
      - task: build
        vars: { COMPOSE_ID: "{{.COMPOSE_ID}}"}
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} pull {{.PULL_CONTAINERS}}
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} up -d {{.PULL_CONTAINERS}}
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} run app ./wait_for_it.sh db:5432 -t 60
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} run {{.CMD}}
      