version: '3'

includes:
  python:
    taskfile: ./Taskfile.python.yml

tasks:
  golang:test:
    cmds:
      - go clean -cache
      - go clean -testcache
      - go test ./... -count=1 -a {{.CLI_ARGS}}

  golang:test:create:
    cmds:
      - task test -- -run TestCreateData -v

  db:run:
    cmds:
      - docker-compose up -d db
  db:down:
    cmds:
      - docker-compose down --remove-orphans --volumes
