version: '3'

includes:
  python:
    taskfile: ./Taskfile.python.yml

tasks:
  golang:test:
    cmds:
      - go clean -cache
      - go clean -testcache
      - go test -v ./... -count=1 -a {{.CLI_ARGS}}

  golang:test:create:
    cmds:
      - task test -- -run TestCreateData -v

  db:run:
    cmds:
      - docker-compose up -d db
  db:down:
    cmds:
      - docker-compose down --remove-orphans --volumes

  git:add_push:
    cmds:
      - git remote set-url git@github.com-dd84ai:darklab8/darklab_training_postgresql.git
      - git remote add noveo git@gitlab-noveo:trainings-anovoselov/trainings-anovoselov-postgersql.git