FROM python:3.9-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY ./requirements.txt ./
COPY ./constraints.txt ./

RUN pip3 install -r requirements.txt -c constraints.txt

COPY manage.py pytest.ini ./
COPY core core
COPY main main

CMD pytest