

stages:
  - test

unit-tests:
  image: docker:20.10.21-cli
  stage: test
  services:
    - docker:dind                    # necessary for docker run
  script:
    - apk update && apk add curl && apk add python3
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - task test

# pages:
#   image: python:3.10
#   stage: deploy
#   needs:
#     - unit-tests
#   script:
#     - pip install -r requirements.txt
#     - mkdocs build
#     - mv site public
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

