version: '3'

tasks:
  clean:
    cmds:
      - sudo rm -R public/* | true
  build:
    cmds:
      - task: clean
      - hugo

  run:dev:
    cmds:
      - alias run_dev="hugo server --disableFastRender --verbose"
      - hugo server --verbose --disableFastRender --buildDrafts
      - echo "run with run_dev"

  install:
    cmds:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.118.2/hugo_0.118.2_linux-amd64.deb

  install:theme:
    cmds:
      - git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
  install:download:
    cmds:
      - git submodule update
