name: Pages

on:
  push: {}
    
jobs:
  github-pages:
    name: Github Pages
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Ensure pip
        run: >
          python3 --version
          python3 -m ensurepip
      - name: Install deps
        run: >
          pip install mkdocs==1.4.1 pymdown-extensions==9.7
      - name: Build docs
        run: >
          mkdocs build
      - uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: ./site
      - name: Deploy to pages
        uses: actions/deploy-pages@v1
        id: deployment
